on: [push]

name: ProvisionKubernetesClusterOnAzure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install az
        run: |
          sudo apt-get update
          sudo apt-get install curl 
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Install terraform
        run: |
          sudo apt-get update && apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && apt-get install terraform -y
      - name: Get az version
        run: az --version
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_SUBSCRIPTION_AZUREWORKSHOP }}'